# Generated by Django 4.1.1 on 2022-09-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='igredients',
        ),
    ]
